title: Jimmy Hung
description: Software, architecture, security, and AI.
url: "https://jmhung.com"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /deepdive/:title/

exclude:
  - README.md
  - DOMAINS.md
